import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import Header from "@/app/components/Header"
import Footer from "@/app/components/Footer"
import "./globals.css";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["700","400"],
  variable: "--font-poppins",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "PMK Squared",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased scroll-smooth`}>
        <Header />
        <main className="md:container mx-auto bg-white shadow-2xl rounded-xl">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}



